steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Python 3.9
    uses: actions/setup-python@v4
    with:
      python-version: '3.9.12'

  - name: Install pip and Upgrade
    run: python -m ensurepip && python -m pip install --upgrade pip

  - name: Install pybind11
    run: pip install pybind11

  - name: Install Other Dependencies
    run: pip install -r requirements.txt

  - name: Build Executable with PyInstaller
    run: pyinstaller --onefile --name junior junior/cli.py

  - name: Upload Artifact
    uses: actions/upload-artifact@v3
    with:
      name: junior-executable
      path: dist/junior
